#!/usr/bin/env python3
"""Run a synthetic LoP positive-control and an unlesioned control.

The positive-control arm uses the EEG-shaped data generated by
``generate-synthetic-lop-positive-control.py``.  After source pretraining, the
warm model receives an explicit representation-gradient lesion (encoder
gradient scale = 0), while the fresh control remains fully trainable.  This
is a detection/validation experiment, not evidence about a real cohort.
"""

from __future__ import annotations

import argparse
import copy
import json
import random
import time
from pathlib import Path
from typing import Any

import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F


DEFAULT_TARGET_SUBJECTS = (4, 5, 6, 7, 8, 9, 10, 11)
DEFAULT_BUDGETS = (0, 5, 10, 25, 50)


def seed_all(seed: int) -> None:
    random.seed(int(seed))
    np.random.seed(int(seed) % (2**32 - 1))
    torch.manual_seed(int(seed))
    torch.use_deterministic_algorithms(True, warn_only=True)


class LatentEEGMLP(nn.Module):
    """Small EEG-shaped decoder with an explicit gradient-scale control."""

    def __init__(self, hidden: int = 8) -> None:
        super().__init__()
        self.encoder = nn.Sequential(nn.Linear(16, hidden), nn.Tanh())
        self.classifier = nn.Linear(hidden, 2)
        self.register_buffer("encoder_gradient_scale", torch.tensor(1.0))

    def set_encoder_gradient_scale(self, value: float) -> None:
        self.encoder_gradient_scale.fill_(float(value))

    def forward(self, values: torch.Tensor) -> torch.Tensor:
        # Generated data stores 16 latent features as 8 channels × 2 halves.
        features = values.reshape(values.shape[0], 8, 2, 1500).mean(dim=-1).reshape(values.shape[0], 16)
        hidden = self.encoder(features)
        scale = self.encoder_gradient_scale
        # Forward values are unchanged; only the encoder's backward path is
        # scaled.  At scale=0 the warm classifier can still update, but the
        # learned representation cannot adapt to a new latent axis.
        hidden = hidden.detach() + scale * (hidden - hidden.detach())
        return self.classifier(hidden)


def _load_subject(root: Path, group: str, subject: int) -> tuple[torch.Tensor, torch.Tensor]:
    data_path = root / group / str(subject) / "data" / "000.npy"
    label_path = root / group / str(subject) / "label" / "000.npy"
    values = np.load(data_path, allow_pickle=False).astype(np.float32, copy=False)
    labels = np.load(label_path, allow_pickle=False).reshape(-1).astype(np.int64, copy=False)
    if values.ndim != 3 or tuple(values.shape[1:]) != (8, 3000) or labels.shape != (values.shape[0],):
        raise ValueError(f"invalid synthetic subject pair: {data_path}")
    return torch.from_numpy(values), torch.from_numpy(labels)


def _load_group(root: Path, group: str, subjects: list[int]) -> tuple[torch.Tensor, torch.Tensor]:
    values, labels = zip(*[_load_subject(root, group, subject) for subject in subjects])
    return torch.cat(values, dim=0), torch.cat(labels, dim=0)


def _batches(values: torch.Tensor, labels: torch.Tensor, batch_size: int, seed: int) -> list[tuple[torch.Tensor, torch.Tensor]]:
    generator = torch.Generator().manual_seed(int(seed))
    indices = torch.randperm(values.shape[0], generator=generator)
    return [(values[index], labels[index]) for index in indices.split(max(1, int(batch_size)))]


def _metrics(model: nn.Module, batches: list[tuple[torch.Tensor, torch.Tensor]]) -> dict[str, float]:
    model.eval()
    losses: list[float] = []
    predictions: list[torch.Tensor] = []
    labels: list[torch.Tensor] = []
    with torch.no_grad():
        for values, target in batches:
            logits = model(values)
            losses.append(float(F.cross_entropy(logits, target).item()))
            predictions.append(logits.argmax(dim=-1))
            labels.append(target)
    predicted = torch.cat(predictions)
    observed = torch.cat(labels)
    f1_values = []
    for cls in range(2):
        tp = int(((predicted == cls) & (observed == cls)).sum())
        fp = int(((predicted == cls) & (observed != cls)).sum())
        fn = int(((predicted != cls) & (observed == cls)).sum())
        denominator = 2 * tp + fp + fn
        f1_values.append(0.0 if denominator == 0 else 2.0 * tp / denominator)
    return {
        "loss": float(np.mean(losses)),
        "accuracy": float((predicted == observed).float().mean()),
        "macro_f1": float(np.mean(f1_values)),
    }


def _probe(
    initial: nn.Module,
    train_batches: list[tuple[torch.Tensor, torch.Tensor]],
    eval_batches: list[tuple[torch.Tensor, torch.Tensor]],
    retention_batches: list[tuple[torch.Tensor, torch.Tensor]],
    budgets: tuple[int, ...],
    lr: float,
) -> tuple[nn.Module, dict[str, Any]]:
    model = copy.deepcopy(initial)
    optimizer = torch.optim.Adam(model.parameters(), lr=float(lr))
    rows: list[dict[str, Any]] = []
    budget_set = set(budgets)

    def record(step: int, train_loss: float | None) -> None:
        evaluation = _metrics(model, eval_batches)
        retention = _metrics(model, retention_batches)
        rows.append({
            "step": int(step),
            "train_loss": train_loss,
            "loss": evaluation["loss"],
            "accuracy": evaluation["accuracy"],
            "macro_f1": evaluation["macro_f1"],
            "retention_loss": retention["loss"],
            "retention_accuracy": retention["accuracy"],
            "retention_macro_f1": retention["macro_f1"],
        })

    record(0, None)
    index = 0
    for step in range(1, max(budgets) + 1):
        values, target = train_batches[index % len(train_batches)]
        index += 1
        model.train()
        loss = F.cross_entropy(model(values), target)
        optimizer.zero_grad(set_to_none=True)
        loss.backward()
        nn.utils.clip_grad_norm_(model.parameters(), 1.0)
        optimizer.step()
        if step in budget_set:
            record(step, float(loss.detach()))
    def auc(key: str) -> float:
        x = np.asarray([row["step"] for row in rows], dtype=np.float64)
        y = np.asarray([row[key] for row in rows], dtype=np.float64)
        if len(x) < 2 or x[-1] <= 0:
            return float(y[-1])
        trapezoid = getattr(np, "trapezoid", None) or getattr(np, "trapz")
        return float(trapezoid(y, x) / x[-1])
    return model, {
        "curve": rows,
        "budgets": [int(item) for item in budgets],
        "final": rows[-1],
        "accuracy_aulc": auc("accuracy"),
        "loss_aulc": auc("loss"),
        "macro_f1_aulc": auc("macro_f1"),
        "retention_accuracy_aulc": auc("retention_accuracy"),
        "retention_loss_aulc": auc("retention_loss"),
    }


def run(args: argparse.Namespace) -> dict[str, Any]:
    root = args.data_root.resolve()
    output = args.output_root.resolve()
    output.mkdir(parents=True, exist_ok=True)
    manifest = json.loads((root / "manifest.json").read_text(encoding="utf-8"))
    source_subjects = [int(item) for item in manifest["source_subjects"]]
    target_subjects = [int(item) for item in manifest["target_subject_order"]]
    retention_subjects = [int(item) for item in manifest["retention_subjects"]]
    source_x, source_y = _load_group(root, "source", source_subjects)
    retention_x, retention_y = _load_group(root, "retention", retention_subjects)
    targets = {}
    for subject in target_subjects:
        values, labels = _load_subject(root, "target", subject)
        midpoint = values.shape[0] // 2
        targets[subject] = (values[:midpoint], labels[:midpoint], values[midpoint:], labels[midpoint:])
    metadata = {
        "schema": "edgeforge.synthetic-eeg-continuous-lop-positive-control.v1",
        "dataset": manifest["dataset"],
        "data_root": str(root),
        "source_subjects": source_subjects,
        "target_subject_order": target_subjects,
        "retention_subjects": retention_subjects,
        "target_split": "first-half-adaptation-last-half-heldout",
        "input_shape": [8, 3000],
        "classes": 2,
        "source_steps": int(args.source_steps),
        "source_lr": float(args.source_lr),
        "adapt_steps": int(max(args.budgets)),
        "budgets": [int(item) for item in args.budgets],
        "adapt_lr": float(args.adapt_lr),
        "batch_size": int(args.batch_size),
        "positive_control": "warm_encoder_gradient_scale_zero_after_source_pretraining",
        "fresh_mode": "random-initialization-at-each-target-stage",
        "warm_mode": "carried-after-previous-stage-final-budget",
        "scientific_conclusion_allowed": False,
    }
    all_runs: list[dict[str, Any]] = []
    for mode in ("positive_control", "no_lesion"):
        for seed in args.seeds:
            started = time.time()
            seed_all(seed)
            warm = LatentEEGMLP()
            source_batches = _batches(source_x, source_y, args.batch_size, seed)
            source_optimizer = torch.optim.Adam(warm.parameters(), lr=float(args.source_lr))
            for _ in range(int(args.source_steps)):
                values, target = source_batches[_ % len(source_batches)]
                warm.train()
                loss = F.cross_entropy(warm(values), target)
                source_optimizer.zero_grad(set_to_none=True)
                loss.backward()
                source_optimizer.step()
            if mode == "positive_control":
                warm.set_encoder_gradient_scale(0.0)
            source_metrics = _metrics(warm, _batches(source_x, source_y, args.batch_size, seed + 1))
            retention_batches = _batches(retention_x, retention_y, args.batch_size, seed + 7000)
            stage_rows: list[dict[str, Any]] = []
            for stage_index, subject in enumerate(target_subjects):
                train_x, train_y, eval_x, eval_y = targets[subject]
                train_batches = _batches(train_x, train_y, args.batch_size, seed + 10_000 + stage_index * 101)
                eval_batches = _batches(eval_x, eval_y, args.batch_size, seed + 10_001 + stage_index * 101)
                fresh_seed = seed + 500_000 + stage_index * 1009 + (0 if mode == "positive_control" else 100_000)
                seed_all(fresh_seed)
                fresh = LatentEEGMLP()
                warm_after, warm_probe = _probe(warm, train_batches, eval_batches, retention_batches, args.budgets, args.adapt_lr)
                fresh_after, fresh_probe = _probe(fresh, train_batches, eval_batches, retention_batches, args.budgets, args.adapt_lr)
                warm = warm_after
                gaps = []
                for warm_row, fresh_row in zip(warm_probe["curve"], fresh_probe["curve"]):
                    gaps.append({
                        "step": int(warm_row["step"]),
                        "fresh_gap": float(fresh_row["accuracy"] - warm_row["accuracy"]),
                        "fresh_loss_gap": float(warm_row["loss"] - fresh_row["loss"]),
                        "fresh_macro_f1_gap": float(fresh_row["macro_f1"] - warm_row["macro_f1"]),
                    })
                stage_rows.append({
                    "stage": stage_index,
                    "subject": subject,
                    "train_sequences": int(train_x.shape[0]),
                    "eval_sequences": int(eval_x.shape[0]),
                    "warm": warm_probe,
                    "fresh": fresh_probe,
                    "gaps": gaps,
                    "fresh_gap_final": float(gaps[-1]["fresh_gap"]),
                    "fresh_loss_gap_final": float(gaps[-1]["fresh_loss_gap"]),
                    "fresh_auc_gap": float(fresh_probe["accuracy_aulc"] - warm_probe["accuracy_aulc"]),
                    "fresh_loss_auc_gap": float(warm_probe["loss_aulc"] - fresh_probe["loss_aulc"]),
                })
            result = {
                "architecture": mode,
                "seed": int(seed),
                "parameters": int(sum(parameter.numel() for parameter in LatentEEGMLP().parameters())),
                "source": source_metrics,
                "stages": stage_rows,
                "mode": mode,
                "elapsed_seconds": float(time.time() - started),
                "scientific_conclusion_allowed": False,
            }
            run_dir = output / mode / f"seed{seed}"
            run_dir.mkdir(parents=True, exist_ok=True)
            (run_dir / "run.json").write_text(json.dumps(result, indent=2) + "\n", encoding="utf-8")
            all_runs.append(result)
    summary = {
        "metadata": metadata,
        "runs": all_runs,
        "architectures": ["positive_control", "no_lesion"],
        "seeds": [int(item) for item in args.seeds],
        "interpretation": "synthetic positive-control validation; not a real-data LoP conclusion",
        "scientific_conclusion_allowed": False,
    }
    (output / "metadata.json").write_text(json.dumps(metadata, indent=2) + "\n", encoding="utf-8")
    (output / "summary.json").write_text(json.dumps(summary, indent=2) + "\n", encoding="utf-8")
    return summary


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--data-root", type=Path, required=True)
    parser.add_argument("--output-root", type=Path, required=True)
    parser.add_argument("--seeds", nargs="+", type=int, default=[4321, 4322, 4323])
    parser.add_argument("--budgets", nargs="+", type=int, default=list(DEFAULT_BUDGETS))
    parser.add_argument("--source-steps", type=int, default=500)
    parser.add_argument("--source-lr", type=float, default=1e-2)
    parser.add_argument("--adapt-lr", type=float, default=5e-3)
    parser.add_argument("--batch-size", type=int, default=64)
    args = parser.parse_args()
    if not args.budgets or args.budgets[0] != 0 or sorted(set(args.budgets)) != list(args.budgets) or max(args.budgets) <= 0:
        parser.error("--budgets must be sorted, unique, start at 0 and include a positive value")
    summary = run(args)
    print(json.dumps({"status": "ok", "runs": len(summary["runs"]), "architectures": summary["architectures"], "seeds": summary["seeds"], "summary": str(args.output_root.resolve() / "summary.json"), "scientific_conclusion_allowed": False}, sort_keys=True))


if __name__ == "__main__":
    main()
